import {t,useLocale} from '../i18n';
import {useState} from 'react';
import {Link,useNavigate,useSearchParams} from 'react-router-dom';
import {Building2,GraduationCap,ArrowRight,ShieldCheck,LoaderCircle} from 'lucide-react';
import {api} from '../api/client';
import {useAuth} from '../auth/AuthContext';
export default function Login(){
  useLocale();

 const {setUser}=useAuth();const navigate=useNavigate();const [params]=useSearchParams();
 const [register,setRegister]=useState(false),[role,setRole]=useState(params.get('role')==='performer'?'performer':'business');
 const [form,setForm]=useState({email:'',password:'',display_name:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{const data=register?await api.register({...form,role}):await api.login({email:form.email,password:form.password});sessionStorage.clear();setUser(data.user);navigate('/challenges',{replace:true})}catch(err){setError(err.message)}finally{setBusy(false)}}
 return <div className="container auth-layout"><section className="auth-story"><span className="hero-kicker">{t("ALEM / ВАШЕ ПРОСТРАНСТВО")}</span><h1>{t("Нужные люди.")}<br/><em>{t("Настоящие задачи.")}</em></h1><p>{t("Один сервис — два личных кабинета. Выберите свою сторону сотрудничества.")}</p><div className="auth-benefit"><Building2/><div><b>{t("Представителю бизнеса")}</b><p>{t("Ваши задачи, оценка ИИ и предложения исполнителей. Доступ к управлению только у вас.")}</p></div></div><div className="auth-benefit"><GraduationCap/><div><b>{t("Исполнителю")}</b><p>{t("Открытые задачи, собственные отклики и прогресс по принятым этапам.")}</p></div></div><span className="auth-security"><ShieldCheck size={17}/>{" "}{t("Права доступа проверяются на сервере")}</span></section><form className="panel auth-form" onSubmit={submit}><div className="auth-tabs"><button type="button" className={!register?'selected':''} onClick={()=>{setRegister(false);setError('')}}>{t("Войти")}</button><button type="button" className={register?'selected':''} onClick={()=>{setRegister(true);setError('')}}>{t("Создать аккаунт")}</button></div><h2>{register?t("Давайте познакомимся"):t("С возвращением")}</h2><p className="muted">{register?t("У каждого аккаунта своя роль и личное пространство."):t("Войдите с email и паролем. Роль определяется вашим аккаунтом.")}</p>{register&&<><div className="role-picker"><button type="button" aria-pressed={role==='business'} className={role==='business'?'selected':''} onClick={()=>setRole('business')}><Building2 size={21}/>{" "}{t("Я — бизнес")}</button><button type="button" aria-pressed={role==='performer'} className={role==='performer'?'selected':''} onClick={()=>setRole('performer')}><GraduationCap size={21}/>{" "}{t("Я — исполнитель")}</button></div><label>{role==='business'?t("Имя или название компании"):t("Ваше имя или название команды")}<input required minLength={2} maxLength={120} autoComplete="organization" value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})}/></label></>}<label>Email<input type="email" required autoComplete="username" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>{t("Пароль")}<input type="password" required minLength={8} maxLength={128} autoComplete={register?'new-password':'current-password'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder={register?t("Не менее 8 символов"):''}/></label>{error&&<div className="alert error" role="alert">{error}</div>}<button className="button primary full" disabled={busy}>{busy?<LoaderCircle className="spin" size={18}/>:<ArrowRight size={18}/>} {register?t("Создать аккаунт"):t("Войти в кабинет")}</button><Link className="back-link" to="/">{t("Вернуться на главную")}</Link></form></div>
}
